Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : Crie um programa que leia a base e a altura de um triângulo e
//calcule sua área.
// Autor(a)    : Alexandre Lemes
// Data atual  : 10/09/2023
Var
   base, altura: inteiro


Inicio
   Escreva("Digite a altura do triangulo:")
   Leia(altura)
   Escreva("Digite a base do triangulo:")
   Leia(Base)
   Escreval("a area do triangulo é:",(base*altura)/2)
Fimalgoritmo