Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama 
// Descrição   : Crie um programa que leia o peso e a altura de uma pessoa e
//exiba o seu Índice de Massa Corporal (IMC).
// Autor(a)    : alexandre LEMES
// Data atual  : 10/09/2023
Var
 peso, altura:real


Inicio
Escreval("Digite seu peso em kg:")
Leia(peso)
Escreval("Digite sua altura em m:")
Leia(altura)
Escreval("o imc é:",peso/altura^2)

Fimalgoritmo