Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : Crie um programa que leia o salário de um funcionário e calcule
// o novo salário com um aumento de 15%.
// Autor(a)    : Alexandre Lemes
// Data atual  : 10/09/2023
Var
   salario:real
Inicio
   Escreval("Digite seu salario:")
   Leia(salario)
   Escreval("Seu salario com 15% de aumento é:", ((salario) + (0.15*salario)))

Fimalgoritmo