Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : 52. Faça um programa que exiba os números de 1 a 10 usando o
//loop "while".
// Autor(a)    : Alexandre Lemes
// Data atual  : 22/09/2023
Var
   numero, contador:inteiro

Inicio
   contador<-1
   enquanto contador<=10 faça
      Escreval(contador)
      contador<-contador+1
   fimenquanto

Fimalgoritmo