Algoritmo "semnome"
// Disciplina   : Lógica de Programação
// Professor   : Obama
// Descrição   : 54. Crie um programa que exiba os números pares de 1 a 50
//usando o loop "while".
// Autor(a)    : ALEXANDRE LEMES
// Data atual  : 23/09/2023
Var
   numero:inteiro

Inicio
   numero<-1
   
   enquanto numero<=50 faça
      se numero mod 2 = 0 entao
         Escreval(numero)
      fimse
      numero<-numero+1
   fimenquanto


Fimalgoritmo